# Generated by Django 3.1.2 on 2020-12-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
